import { Vehicle } from "@/lib/types";

export const VEHICLES: Vehicle[] = [
  {
    id: "1",
    zip: "02116",
    make: "Toyota",
    model: "Camry",
    trim: "SE",
    year: 2021,
    color: "White",
    mileage: 24500,
    price: 21950,
    imageUrl: "/vehicles/toyota-camry-white.jpeg",
  },
  {
    id: "2",
    zip: "02116",
    make: "Honda",
    model: "Civic",
    trim: "EX",
    year: 2020,
    color: "Black",
    mileage: 31000,
    price: 18900,
    imageUrl: "/vehicles/honda-civic-black.jpeg",
  },
  {
    id: "3",
    zip: "10001",
    make: "Tesla",
    model: "Model 3",
    trim: "Long Range",
    year: 2022,
    color: "Blue",
    mileage: 12000,
    price: 35900,
    imageUrl: "/vehicles/tesla-model3-blue.avif",
  },
  {
    id: "4",
    zip: "94105",
    make: "Ford",
    model: "F-150",
    trim: "XLT",
    year: 2019,
    color: "Gray",
    mileage: 48000,
    price: 27950,
    imageUrl: "/vehicles/ford-f150-gray.jpeg",
  },
  {
    id: "5",
    zip: "10001",
    make: "Toyota",
    model: "RAV4",
    trim: "XLE",
    year: 2021,
    color: "Red",
    mileage: 22000,
    price: 28900,
    imageUrl: "/vehicles/toyota-rav4-red.webp",
  },
  {
    id: "6",
    zip: "02116",
    make: "Tesla",
    model: "Model Y",
    trim: "Performance",
    year: 2023,
    color: "White",
    mileage: 8000,
    price: 47900,
    imageUrl: "/vehicles/tesla-modely-white.avif",
  },
  {
    id: "7",
    zip: "02116",
    make: "Subaru",
    model: "Outback",
    trim: "Premium",
    year: 2020,
    color: "Green",
    mileage: 36000,
    price: 24500,
    imageUrl: "/vehicles/subaru-outback-green.avif",
  },
  {
    id: "8",
    zip: "02116",
    make: "BMW",
    model: "3 Series",
    trim: "330i",
    year: 2021,
    color: "Silver",
    mileage: 18000,
    price: 33900,
    imageUrl: "/vehicles/bmw-330i-silver.jpeg",
  },
  {
    id: "9",
    zip: "02116",
    make: "Hyundai",
    model: "Elantra",
    trim: "SEL",
    year: 2019,
    color: "Blue",
    mileage: 42000,
    price: 14900,
    imageUrl: "/vehicles/hyundai-elantra-blue.avif",
  },
  {
    id: "10",
    zip: "02116",
    make: "Audi",
    model: "Q5",
    trim: "Premium Plus",
    year: 2022,
    color: "Gray",
    mileage: 15000,
    price: 41900,
    imageUrl: "/vehicles/audi-q5-gray.webp",
  },
  {
    id: "11",
    zip: "10001",
    make: "Honda",
    model: "Accord",
    trim: "Sport",
    year: 2021,
    color: "White",
    mileage: 27000,
    price: 25900,
    imageUrl: "/vehicles/honda-accord-white.jpeg",
  },
  {
    id: "12",
    zip: "10001",
    make: "Nissan",
    model: "Altima",
    trim: "SV",
    year: 2020,
    color: "Black",
    mileage: 33000,
    price: 17500,
    imageUrl: "/vehicles/nissan-altima-black.jpeg",
  },
  {
    id: "13",
    zip: "10001",
    make: "Tesla",
    model: "Model Y",
    trim: "Long Range",
    year: 2022,
    color: "Gray",
    mileage: 14000,
    price: 44900,
    imageUrl: "/vehicles/tesla-modely-gray.avif",
  },
  {
    id: "14",
    zip: "10001",
    make: "Ford",
    model: "Escape",
    trim: "SE",
    year: 2019,
    color: "Blue",
    mileage: 50000,
    price: 16900,
    imageUrl: "/vehicles/ford-escape-blue.jpeg",
  },
  {
    id: "15",
    zip: "94105",
    make: "Chevrolet",
    model: "Bolt",
    trim: "LT",
    year: 2021,
    color: "White",
    mileage: 19000,
    price: 21900,
    imageUrl: "/vehicles/chevy-bolt-white.avif",
  },
  {
    id: "16",
    zip: "94105",
    make: "Toyota",
    model: "Prius",
    trim: "LE",
    year: 2020,
    color: "Silver",
    mileage: 38000,
    price: 19900,
    imageUrl: "/vehicles/toyota-prius-silver.jpeg",
  },
  {
    id: "17",
    zip: "94105",
    make: "Mazda",
    model: "CX-5",
    trim: "Touring",
    year: 2021,
    color: "Red",
    mileage: 26000,
    price: 26900,
    imageUrl: "/vehicles/mazda-cx5-red.jpeg",
  },
  {
    id: "18",
    zip: "94105",
    make: "Volkswagen",
    model: "Golf GTI",
    trim: "S",
    year: 2019,
    color: "Black",
    mileage: 41000,
    price: 22900,
    imageUrl: "/vehicles/vw-golfgti-black.webp",
  },
  {
    id: "19",
    zip: "94105",
    make: "Hyundai",
    model: "Ioniq 5",
    trim: "SE",
    year: 2022,
    color: "Blue",
    mileage: 12000,
    price: 38900,
    imageUrl: "/vehicles/hyundai-ioniq5-blue.webp",
  },
  {
    id: "20",
    zip: "10001",
    make: "Jeep",
    model: "Wrangler",
    trim: "Sport S",
    year: 2018,
    color: "Green",
    mileage: 62000,
    price: 27900,
    imageUrl: "/vehicles/jeep-wrangler-green.avif",
  },
];
